import { QuestItemType } from "@/types/quest";
import { BonusType } from "@/types/quest";

export const QuestDailyItemList: QuestItemType[] = [
    {
        name: 'space-battle',
        rarity: '',
        content: 'Deal 500 Damage by rocket',
        totalBonusDay: 1000,
        currentBonusDay: 999,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },
    {
        name: 'space-battle',
        rarity: '',
        content: 'Deal 500 Damage by rocket',
        totalBonusDay: 5,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },
    {
        name: 'space-battle',
        rarity: '',
        content: 'Deal 500 Damage by rocket',
        totalBonusDay: 500,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },
    {
        name: 'guide',
        rarity: 'normal',
        content: 'Destroy Linkor5 times by rocket',
        totalBonusDay: 500,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },
    {
        name: 'xp',
        rarity: 'mythic',
        content: 'Earn 100 Experience',
        totalBonusDay: 500,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },
    {
        name: 'xp',
        rarity: 'legendary',
        content: 'Earn 100 Experience',
        totalBonusDay: 500,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },

    {
        name: 'space-battle',
        rarity: 'rare',
        content: 'Daily check in to the two main socials of Star Defender',
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: true,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 1 },
        ],
    },
]

export const QuestWeeklyItemList: QuestItemType[] = [
    {
        name: 'space-battle',
        rarity: '',
        content: "vrajeskim korablyam nanesite 500 urona vrajeskim korablyam",
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 5 },
        ],
    },
    {
        name: 'space-battle',
        rarity: '',
        content: "vrajeskim korablyam nanesite 500 urona vrajeskim korablyam",
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 5 },
        ],
    },
    {
        name: 'space-battle',
        rarity: '',
        content: "vrajeskim korablyam nanesite 500 urona vrajeskim korablyam",
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 5 },
        ],
    },
    {
        name: 'space-battle',
        rarity: 'normal',
        content: "vrajeskim korablyam nanesite 500 urona vrajeskim korablyam",
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 5 },
        ],
    },
    {
        name: 'space-battle',
        rarity: 'mythic',
        content: "vrajeskim korablyam nanesite 500 urona vrajeskim korablyam",
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 5 },
        ],
    },
    {
        name: 'space-battle',
        rarity: 'legendary',
        content: "vrajeskim korablyam nanesite 500 urona vrajeskim korablyam",
        totalBonusDay: 1,
        currentBonusDay: 0,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 5 },
        ],
    },


]

export const QuestItemList: QuestItemType[] = [
    {
        name: 'red-triangle',
        rarity: 'normal',
        content: 'Amet, luctus leo, platea orci, cursus in nisi cursus dictum libero, ipsum fgeb',
        totalBonusDay: 1,
        currentBonusDay: 0 ,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 14 },
        ],
    },
    {
        name: 'star-defender',
        rarity: 'rare',
        content: 'Amet, luctus leo, platea orci, cursus in nisi cursus dictum libero, ipsum fgeb',
        totalBonusDay: 3,
        currentBonusDay: 2,
        isWaiting: true,
        waitingTime: 3850,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day3', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
        ],
    } ,
    {
        name: 'rock-alliance',
        rarity: 'mythic',
        content: 'Amet, luctus leo, platea orci, cursus in nisi cursus dictum libero, ipsum fgeb',
        totalBonusDay: 7,
        currentBonusDay: 6,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day3', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day4', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day5', bonusCount: 7 },
            { isReceived: false, isMissed: true, isRewardDay: false, day: 'Day6', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day7', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
        ],
    },
    {
        name: 'moai-heads',
        rarity: 'legendary',
        content: 'Amet, luctus leo, platea orci, cursus in nisi cursus dictum libero, ipsum fgeb',
        totalBonusDay: 14,
        currentBonusDay: 7,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day3', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day4', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day5', bonusCount: 7 },
            { isReceived: false, isMissed: true, isRewardDay: false, day: 'Day6', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day7', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day8', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day9', bonusCount: 7 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day10', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day11', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day12', bonusCount: 7 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day13', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day14', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
        ],
    },
    {
        name: 'vorpal',
        rarity: 'vorpal',
        content: 'Amet, luctus leo, platea orci, cursus in nisi cursus dictum libero, ipsum fgeb',
        totalBonusDay: 30,
        currentBonusDay: 29,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day3', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day4', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day5', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day6', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day7', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day8', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day9', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day10', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day11', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day12', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day13', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day14', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day15', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day16', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day17', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day18', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day19', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day20', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day21', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day22', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day23', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day24', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day25', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day26', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day27', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day28', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
            { isReceived: false, isMissed: true, isRewardDay: false, day: 'Day29', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day30', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
        ],
    }
]

export const BonusList: BonusType[] = [
    { isBonusDay: false, isRewardDay: true, bonusCount: 4 },
    { isBonusDay: true, isRewardDay: false, bonusCount: 24 },
    { isBonusDay: true, isRewardDay: false, bonusCount: 24 },
    { isBonusDay: true, isRewardDay: false, bonusCount: 24 },
    { isBonusDay: true, isRewardDay: false, bonusCount: 24 },
]

export const RewardList: BonusType[] = [
    { isBonusDay: false, isRewardDay: true, bonusCount: 4 },
]
