import { QuestItemType } from "@/types/quest";

export const QuestItemList: QuestItemType[] = [
    {
        name: 'red-triangle',
        totalBonusDay: 1,
        currentBonusDay: 0 ,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day1', bonusCount: 14 },
        ],
    },
    {
        name: 'star-defender',
        totalBonusDay: 3,
        currentBonusDay: 2,
        isWaiting: true,
        waitingTime: 3850,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day3', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
        ],
    } ,
    {
        name: 'rock-alliance',
        totalBonusDay: 7,
        currentBonusDay: 6,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day3', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day4', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day5', bonusCount: 7 },
            { isReceived: false, isMissed: true, isRewardDay: false, day: 'Day6', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day7', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
        ],
    },
    {
        name: 'moai-heads',
        totalBonusDay: 14,
        currentBonusDay: 7,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day3', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day4', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day5', bonusCount: 7 },
            { isReceived: false, isMissed: true, isRewardDay: false, day: 'Day6', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day7', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: false, isMissed: false, isRewardDay: true, day: 'Day8', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day9', bonusCount: 7 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day10', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day11', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day12', bonusCount: 7 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day13', bonusCount: 24 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Day14', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: false, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
        ],
    },
    {
        name: 'vorpal',
        totalBonusDay: 30,
        currentBonusDay: 29,
        isWaiting: false,
        waitingTime: 0,
        rewardsList: [
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day1', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day2', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day3', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day4', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day5', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day6', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day7', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day8', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day9', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day10', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day11', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day12', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day13', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day14', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day15', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day16', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day17', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day18', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day19', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day20', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day21', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day22', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day23', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day24', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 3 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day25', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day26', bonusCount: 7 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day27', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day28', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
            { isReceived: false, isMissed: true, isRewardDay: false, day: 'Day29', bonusCount: 24 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Day30', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 14 },
            { isReceived: true, isMissed: false, isRewardDay: false, day: 'Bonus', bonusCount: 30 },
        ],
    }
]
